# Identificadores únicos do projeto no SonarCloud
sonar.organization=elidjeidevoper-startup_superfluxo
sonar.projectKey=elidjeidevoper-startup
sonar.projectName=SuperFluxo

# Caminho para o código-fonte (analisa tudo dentro da pasta src)
sonar.sources=src

# Codificação do código fonte
sonar.sourceEncoding=UTF-8

# Exclusões opcionais (ex: se usar bibliotecas externas baixadas localmente)
# sonar.exclusions=src/lib/**